name: "urvaragro"
title: "urvaragro"
description: "urvaragro Advisory Pvt. Ltd. | A Global Asset Management Company"
meta_description: "urvaragro Advisory Pvt. Ltd. | A Global Asset Management Company"
logo: 'assets/img/logo.png'
favicon: 'assets/img/favicon.png'
paginate: 12
baseurl: ''
url: 'https://urvaragro-staging.github.io/'
email: 'dhammapal@urvaragro.com'
locale: en_US
seo:
  keywords: 'urvaragro'
  site_name: urvaragro
og:
  type: "website"

plugins: 
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-sitemap

sass:
  style: compressed
        
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
markdown: kramdown
highlighter: rouge

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
# Google Tag Manager Integration
google-tag-manager-id: GTM-MTFQ8TF
google-analytics-id: G-E0ZW5NRN6K

## Verify ownership with several services at once using the following format
webmaster_verifications:
  google: xVEmwX6PFrFabJWC30aDEuvWSbnr11QegyS-B9UbDB8
  bing: 1E642F36EC0479DC69135F989CDC274A
  yandex: 43039f2f4b41e2c3
  baidu: 1234
  facebook: 1234
  ahrefs: 51bddb95e8fc130687b6ef65736ca7afb4c52168083b13a5e11eb5f1f2a536d7

  